### ISSUE TITLE
converting to android-aarch64 not working

### ISSUE THREAD

**Issue by ItzxDwi** [pmmp/php-build-scripts#192] opened 2024-05-07 09:05 UTC
```/compile.sh -t android-aarch64 -x -j14 -P5 -g
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependencies
[opt] Set target to android-aarch64
[opt] Doing cross-compile
[opt] Set make threads to 14
[opt] Will enable GD2
[opt] Compiling with configuration for PocketMine-MP 5
[INFO] Cross-compiling for Android ARMv8 (aarch64)
Warning:  OPcache cannot be used on static builds; this may have a negative effect on performance
Warning:  Xdebug cannot be built in static mode
[PHP 8.2.17] downloading... done!
[zlib 1.3.1] downloading... configuring... compiling... installing... done!
[gmp 6.3.0] downloading... configuring... compiling... installing... done!
[openssl 3.2.1] downloading... configuring... compiling... installing... done!
[curl curl-8_7_1] downloading... configuring... compiling... installing... done!
[sasl2 2.1.28] downloading...checking... compiling...  installing... done!
[zstd 1.5.5] downloading... checking... compiling... installing... done!
[librdkafka 2.1.1] downloading... checking... compiling... installing...
Error: Process completed with exit code 2.```

**Comment by DaisukeDaisuke** [comment] 2024-05-07 09:19
You are using a modified compile.sh and this is unsupported
However, unless you have install.log and/or compile.sh it is impossible to identify the cause
If you do not want to build `librdkafka`, use compile.sh from this repository

**Comment by ItzxDwi** [comment] 2024-05-07 09:21
> You are using a modified compile.sh and this is unsupported However, unless you have install.log and/or compile.sh it is impossible to identify the cause If you do not want to build `librdkafka`, use compile.sh from this repository

yes, i use the nethergames one

**Comment by DaisukeDaisuke** [comment] 2024-05-07 09:24
Sorry, forking isn't supported(I'm not a moderator here)
But if you send me your `install.log` I might be able to tell you something

**Comment by ItzxDwi** [comment] 2024-05-07 09:27
> Sorry, forking isn't supported(I'm not a moderator here) But if you send me your `install.log` I might be able to tell you something

idk how to get the install.log
https://github.com/ItzxDwi/AndroidPHP/actions/runs/8982554509

**Comment by ItzxDwi** [comment] 2024-05-07 09:29
maybe its related to the amount of the threads?

**Comment by ItzxDwi** [comment] 2024-05-07 09:32
@DaisukeDaisuke

**Comment by DaisukeDaisuke** [comment] 2024-05-07 10:40
It seems that `libzstd` cannot be statically built(fork)
I couldn't find a solution

I recommend closing the issue as it has nothing to do with the repository
```
[ 31%] Linking C shared library librdkafka.so
/home/daiuskedaisuke/aarch64-linux-musl/bin/../lib/gcc/aarch64-linux-musl/9.4.0/../../../../aarch64-linux-musl/bin/ld: attempted static link of dynamic object `/home/daiuskedaisuke/Downloads/php-build-scripts/bin/php7/lib/libzstd.so'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rdkafka.dir/build.make:1317: src/librdkafka.so.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/rdkafka.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Consolidate compiler generated dependencies of target rdkafka
[  1%] Linking C shared library librdkafka.so
/home/daiuskedaisuke/aarch64-linux-musl/bin/../lib/gcc/aarch64-linux-musl/9.4.0/../../../../aarch64-linux-musl/bin/ld: attempted static link of dynamic object `/home/daiuskedaisuke/Downloads/php-build-scripts/bin/php7/lib/libzstd.so'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rdkafka.dir/build.make:1317: src/librdkafka.so.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/rdkafka.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by ItzxDwi** [comment] 2024-05-07 10:44
> It seems that `libzstd` cannot be statically built(fork) I couldn't find a solution
> 
> I recommend closing the issue as it has nothing to do with the repository
> 
> ```
> [ 31%] Linking C shared library librdkafka.so
> /home/daiuskedaisuke/aarch64-linux-musl/bin/../lib/gcc/aarch64-linux-musl/9.4.0/../../../../aarch64-linux-musl/bin/ld: attempted static link of dynamic object `/home/daiuskedaisuke/Downloads/php-build-scripts/bin/php7/lib/libzstd.so'
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/CMakeFiles/rdkafka.dir/build.make:1317: src/librdkafka.so.1] Error 1
> make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/rdkafka.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> Consolidate compiler generated dependencies of target rdkafka
> [  1%] Linking C shared library librdkafka.so
> /home/daiuskedaisuke/aarch64-linux-musl/bin/../lib/gcc/aarch64-linux-musl/9.4.0/../../../../aarch64-linux-musl/bin/ld: attempted static link of dynamic object `/home/daiuskedaisuke/Downloads/php-build-scripts/bin/php7/lib/libzstd.so'
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/CMakeFiles/rdkafka.dir/build.make:1317: src/librdkafka.so.1] Error 1
> make[1]: *** [CMakeFiles/Makefile2:189: src/CMakeFiles/rdkafka.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> ```

how do i compile it without statically?

**Comment by DaisukeDaisuke** [comment] 2024-05-07 10:49
I tried various things, but it didn't work
I recommend renting a VPS server, PMMP server, etc., and setting up a server there

**Comment by ItzxDwi** [comment] 2024-05-07 10:55
> I tried various things, but it didn't work I recommend renting a VPS server, PMMP server, etc., and setting up a server there

i know, im using localhost to testing plugins. Also random question, is witherhost using linux?

**Closed as completed** 2024-05-07 11:02 UTC
