### ISSUE TITLE
compile.sh

### ISSUE THREAD

**Issue by dksslq** [pmmp/php-build-scripts#44] opened 2018-02-23 12:50 UTC
most of aarch64 gcc are not support '-m64'  flag,,,check it~,should  add sum  judge string........

**Comment by dktapps** [comment] 2018-03-05 09:37
duplicate of #14 

additionally, none of the development team has aarch64 hardware which is not phones, so this is not possible for us to test.

**Closed by dktapps** 2018-03-05 09:37 UTC
