### ISSUE TITLE
Compilation is not completing

### ISSUE THREAD

**Issue by Govdim** [pmmp/php-build-scripts#109] opened 2020-10-29 17:08 UTC
At the last stage of PHP compilation, the process is interrupted with the following error:

Makefile:1154: recipe for target 'ext/morton/morton.lo' failed
make: *** [ext/morton/morton.lo] Error 1

branch: master
OS: Ubuntu 18.04

**Comment by dktapps** [comment] 2020-10-29 17:35
Provide the whole log file.

**Comment by Govdim** [comment] 2020-10-29 20:03
[install.log](https://github.com/pmmp/php-build-scripts/files/5460948/install.log)

**Comment by dktapps** [comment] 2020-10-29 20:36
The hardware specifications of the CPU are relevant here, also which flags you passed to `compile.sh`.

**Comment by Govdim** [comment] 2020-10-29 21:18
Without flags, the result is the same

**Comment by Encritary** [comment] 2020-11-04 09:23
try passing ``-t linux64``

**Comment by dktapps** [comment] 2020-11-04 10:23
That shouldn't make any difference.

**Comment by Govdim** [comment] 2020-11-04 16:36
Does it matter that Linux was launched in the "VirtualBox" program?

**Comment by SOF3** [comment] 2020-11-04 16:57
As long as your host is using a "normal" architecture (like amd64), virtual machines shall not affect anything.

**Comment by dktapps** [comment] 2020-11-04 17:27
Yes, it can matter. I experienced this issue in virtualbox, but only when AVX2 was enabled.

**Comment by dktapps** [comment] 2020-11-04 23:51
Please provide the content of `/proc/cpuinfo` from inside your VM.

**Comment by Govdim** [comment] 2020-11-05 11:09
[cpuinfo.txt](https://github.com/pmmp/php-build-scripts/files/5493903/cpuinfo.txt)

**Comment by dktapps** [comment] 2020-11-05 11:15
Interesting, I didn't know AVX was supported on Ryzen CPUs.

It looks like this is caused by the same issue I faced (AVX2 is supported on your CPU but not BMI2).

**Comment by Forceflow** [comment] 2020-11-10 14:10
I've deplyoyed a possible fix in branch: https://github.com/Forceflow/libmorton/tree/avx_bmi_fix

**Comment by Forceflow** [comment] 2020-11-11 15:34
Dev version now has fix, will push to main soon.
https://github.com/Forceflow/libmorton/tree/develop

**Comment by dktapps** [comment] 2020-11-11 15:58
Awesome, thanks for your time @Forceflow

**Comment by Forceflow** [comment] 2020-11-12 08:08
> 
> 
> Awesome, thanks for your time @Forceflow

No problem, good luck with your project

**Comment by dktapps** [comment] 2020-12-09 00:11
Fixed by bdce80c6c2e64524b6de56772c16096679abfc8f.

**Closed by dktapps** 2020-12-09 00:11 UTC
